apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: s3bucket
  namespace: fast-video
spec:
  type: bindings.aws.s3
  version: v1
  metadata:
    - name: bucket
      value: "processed-bucket-techchallenge"
    - name: region
      value: "us-east-1"
    - name: enableIAM
      value: "true"
auth:
  secretStore: kubernetes
