apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: video-start-processing-subscription
  namespace: fast-video
spec:
  topic: processing-video-consumer.fifo
  route: /video-start-processing
  pubsubname: snssqs-pubsub
scopes:
  - processing-video-consumer
