 @MessageConsumer_HostAddress = http://localhost:5148

POST {{MessageConsumer_HostAddress}}/video-start-processing
Accept: application/json
Content-Type: application/json

{
  "processId": "DC8CB4DF-E7C3-423F-85E9-DD0EA26DECF0",
  "VideoName": "fiap.mp4"
}

###
