apiVersion: v1
kind: ConfigMap
metadata:
  name: video-screenshot-processor-configmap
  namespace: fast-video
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5148"
  AppConfiguration__ffmpegPath: "/usr/bin/ffmpeg"
  AppConfiguration__DaprHttpUrl: "http://localhost:3500"
  AppConfiguration__DaprGrpcUrl: "http://localhost:50001"
  AppConfiguration__PubSubComponent: "snssqs-pubsub"
