apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-screenshot-processor-dep
  namespace: fast-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-screenshot-processor
  template:
    metadata:
      labels:
        app: video-screenshot-processor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "processing-video-consumer"
        dapr.io/app-port: "5148"
        dapr.io/app-protocol: "http"
    spec:
      serviceAccountName: notificacao-api-sa
      containers:
      - name: video-screenshot-processor
        image: bergzado/video-screenshot-processor:latest
        ports:
        - containerPort: 5148
        envFrom:
        - configMapRef:
            name: video-screenshot-processor-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 5148
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5148
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

