apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-screenshot-processor-hpa
  namespace: video
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-screenshot-processor-dep
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
