apiVersion: v1
kind: Service
metadata:
  name: video-screenshot-processor-svc
  namespace: video
spec:
  selector:
    app: video-screenshot-processor
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 5148
