apiVersion: v1
kind: Service
metadata:
  name: video-screenshot-processor-svc
  namespace: fast-video
spec:
  selector:
    app: video-screenshot-processor
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 5148

---
apiVersion: v1
kind: Service
metadata:
  name: processing-video-consumer-dapr-lb
  namespace: fast-video
spec:
  selector:
    app: video-screenshot-processor
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 3500
