apiVersion: v1
kind: ServiceAccount
metadata:
  name: notificacao-api-sa
  namespace: fast-video
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::585008076257:role/notificacao-api-irsa-role