apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-screenshot-processor.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.environment | quote }}
  ASPNETCORE_URLS: {{ .Values.config.urls | quote }}
  AppConfiguration__ffmpegPath: {{ .Values.config.ffmpegPath | quote }}
  AppConfiguration__DaprHttpUrl: {{ .Values.config.daprHttpUrl | quote }}
  AppConfiguration__DaprGrpcUrl: {{ .Values.config.daprGrpcUrl | quote }}
