name: CI/CD Build & Deploy

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to production?'
        required: true
        type: choice
        options:
          - true
          - false

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd src/Application/VideoScreenshot.MessageConsumer
          dotnet restore VideoScreenshot.MessageConsumer.csproj

      - name: Build and publish
        run: |
          cd src/Application/VideoScreenshot.MessageConsumer
          dotnet publish VideoScreenshot.MessageConsumer.csproj -c Release -o ../../../../app-publish /p:UseAppHost=false

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/processor-api:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/processor-api:${{ github.sha }} .

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/processor-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/processor-api:${{ github.sha }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install AWS CLI
        run: |
          sudo apt update && sudo apt install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for AWS EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name video-processor-eks-cluster

      - name: Deploy to EKS Cluster
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: |
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/service-account.yaml
          kubectl apply -f kubernetes/configmap.yaml
          kubectl apply -f kubernetes/secrets.yaml
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/hpa.yaml
          kubectl apply -f dapr/components/s3-component.yaml
          kubectl apply -f dapr/components/sns-component.yaml
          kubectl rollout status deployment/video-screenshot-processor-dep -n fast-video
